-- MoneyTrack: persistent monthly budgets
-- Run this once in Supabase SQL Editor.

create table if not exists public.money_budgets (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  month date not null,
  category text not null,
  amount numeric(12,2) not null default 0 check (amount >= 0),
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  unique(user_id, month, category)
);

alter table public.money_budgets enable row level security;

drop policy if exists "Users can view own budgets" on public.money_budgets;
drop policy if exists "Users can insert own budgets" on public.money_budgets;
drop policy if exists "Users can update own budgets" on public.money_budgets;
drop policy if exists "Users can delete own budgets" on public.money_budgets;

create policy "Users can view own budgets"
  on public.money_budgets for select
  using (auth.uid() = user_id);

create policy "Users can insert own budgets"
  on public.money_budgets for insert
  with check (auth.uid() = user_id);

create policy "Users can update own budgets"
  on public.money_budgets for update
  using (auth.uid() = user_id)
  with check (auth.uid() = user_id);

create policy "Users can delete own budgets"
  on public.money_budgets for delete
  using (auth.uid() = user_id);

create index if not exists money_budgets_user_month_idx
  on public.money_budgets(user_id, month);
